# Generated by Django 6.0 on 2025-12-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
