# Generated by Django 5.2.9 on 2025-12-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
    ]
